#framework:
#    mailer:
#        dsn: 'smtp://smtp.gmail.com:587?encryption=tls&auth_mode=login&username=apollift@gmail.com&password=ApolliftTeam'

# framework:
#     mailer:
#         dsn: 'sendmail://default'

framework:
    mailer:
        dsn: 'smtp://localhost:25'
