security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        # Configurez votre fournisseur de données utilisateur, par exemple à partir de la base de données
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: accueil # Rediriger vers la page d'accueil après la connexion
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
    
    role_hierarchy:
        ROLE_SUPERVISEUR: ROLE_USER
        ROLE_ADMIN: ROLE_SUPERVISEUR