#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_equipement_modif:
    path: /admin/equipement/modif/{id}
    controller: App\Controller\Admin\EquipementController::modifEquipement
    methods: ['GET', 'POST']

admin_equipement_suppression:
    path: /admin/equipement/suppression/{id}
    controller: App\Controller\Admin\EquipementController::suppressionEquipement
    methods: ['GET']

confirm_registration:
    path: '/confirm-registration/{token}'
    controller: App\Controller\RegistrationController::confirmRegistration

footer_politique_confidentialite:
    path: /footer/politique-confidentialite
    controller: App\Controller\Footer\PolitiqueConfidentialiteController::politiqueConfidentialite

footer_politique_cookies:
    path: /footer/politique-cookies
    controller: App\Controller\Footer\PolitiqueCookiesController::politiqueCookies

footer_conditions_generales:
    path: /footer/conditions-generales
    controller: App\Controller\Footer\ConditionsGeneralesController::conditionsGenerales